config/routes.rb
Rails.application.routes.draw do
  devise_for :houses
  root to: "pages#toppage"
  resources :users
  resources :rules
  resources :money
  resources :works
  resources :todos
  resources :schedules
  resources :chats
end

app/models/money.rb
class Money < ApplicationRecord
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :item_name
    validates :price, format: { with: /\A[0-9]+\z/ }
    validates :price, numericality: true
  end
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  before_action :authenticate_house!
  before_action :set_users, only: [:index, :new, :edit]
  before_action :set_find_money, only: [:show, :edit, :update, :destroy]
  before_action :set_redirect, only: [:show, :edit]

  def index
    @money = Money.all.order(id: 'DESC')
  end

  def new
    @money = Money.new
  end

  def create
    @users = User.all
    @money = Money.new(money_params)
    if @money.save
      redirect_to money_index_path
    else
      @users = User.where(house_id: current_house.id)
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @money.update(money_params)
      redirect_to money_path(@money)
    else
      @users = User.where(house_id: current_house.id)
      render :edit
    end
  end

  def destroy
    @money.destroy
    redirect_to money_index_path
  end

  private

  def money_params
    params.require(:money).permit(:item_name, :price, :user_name).merge(house_id: current_house.id)
  end

  def set_users
    @users = User.where(house_id: current_house.id)
  end

  def set_find_money
    @money = Money.find(params[:id])
  end

  def set_redirect
    redirect_to root_path if @money.house_id != current_house.id
  end
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/views/money/edit.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">支出編集</h3>
      <p class="lead text-muted">支出の編集が可能です。</p>
      <p>
        <%= link_to "詳細に戻る", money_path(@money.id), class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<div class="card col-sm-6 mx-auto mb-5">
  <div class="card-body text-center mx-auto">
    <h4 class="mt-1 mb-3">支出編集</h4><br>
    <%= form_with(model: @money, local: true) do |form| %>
     <%= render 'layouts/error_messages', model: form.object %>

      <div class="form-group">
        <%= form.select :user_name, @users.map{ |user| user.user_name }, include_blank: "支払者を選択" %>
      </div>

      <div class="form-group">
        <%= form.text_field :item_name, autocomplete: "off", placeholder: "商品" %>
      </div>

      <div class="form-group">
        <%= form.text_field :price, autocomplete: "off", placeholder: "金額" %>
      </div>

      <div class="actions">
        <%= form.submit "変更", :class => "btn btn-outline-dark disabled" %>
      </div>

    <% end %>
  </div>
</div>

app/views/money/index.html.erb
<section class="pt-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">マネー管理</h3>
      <p class="lead text-muted">支出の登録が可能です。クリックすると詳細画面へ移動します。</p>
      <p>
        <%= link_to "支出登録", new_money_path, class: "btn btn-outline-info my-2" %>
        <%= link_to "メニューに戻る", root_path, class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<main class="container">
  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <% @users.each do |user| %>
      <div class="col">
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 fw-normal">
              <%= user.user_name %>
            </h4>
          </div>
          <div class="card-body">
            <h3 class="card-title pricing-card-title">
              <% @sum = 0 %>
              <% @money.each do |money| %>
                <% if current_house.id == money.house_id %>
                  <% if user.user_name == money.user_name %>
                    <% @sum += money.price %>
                  <% end %>
                <% end %>
              <% end %>
              ￥<%= @sum %><small class="text-muted"> /合計</small>
            </h3>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</main>
<div class="card col-11 mx-auto mb-5">
  <div class="table-responsive table-hover table-borderless col-9 mx-auto text-center">
    <table class="table">
      <thead>
        <tr>
          <th>支払者</th>
          <th>商品名</th>
          <th>金額</th>
          <th>詳細</th>
        </tr>
      </thead>
      <% @money.each do |money| %>
        <% if current_house.id == money.house_id %>
          <tbody>
            <tr>
              <td>
                <%= money.user_name %>
              </td>
              <td>
                <%= money.item_name %>
              </td>
              <td>
                <%= money.price %>円
              </td>
              <td>
                <%= link_to "詳細", money_path(money.id), class: "btn btn-outline-secondary btn-sm" %>
              </td>
            </tr>
          </tbody>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/money/new.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">支出登録</h3>
      <p class="lead text-muted">支出の登録が可能です。</p>
      <p>
        <%= link_to "一覧に戻る", money_index_path, class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<div class="card col-sm-6 mx-auto mb-5">
  <div class="card-body text-center mx-auto">
    <h4 class="mt-1 mb-3">支出内容</h4><br>
    <%= form_with(model: @money, local: true) do |form| %>
     <%= render 'layouts/error_messages', model: form.object %>

      <div class="form-group">
        <%= form.select :user_name, @users.map{ |user| user.user_name }, include_blank: "支払者を選択" %>
      </div>

      <div class="form-group">
        <%= form.text_field :item_name, autocomplete: "off", placeholder: "商品" %>
      </div>

      <div class="form-group">
        <%= form.text_field :price, autocomplete: "off", placeholder: "金額" %>
      </div>

      <div class="actions">
        <%= form.submit "登録", :class => "btn btn-outline-dark disabled" %>
      </div>

    <% end %>
  </div>
</div>

app/views/money/show.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">支出詳細</h3>
      <p class="lead text-muted">支出の編集・削除が可能です。</p>
      <p>
        <%= link_to "編集", edit_money_path, class: "btn btn-outline-success my-2" %>
        <%= link_to "削除", money_path, method: :delete, class: "btn btn-outline-danger my-2" %>
        <%= link_to "一覧に戻る", money_index_path, class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<main>
  <div class="card col-sm-10 mx-auto mb-5">
    <div class="card-body text-center mx-auto">
      <% if current_house.id == @money.house_id %>
        <div class="col my-5">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4 class="card-text">
                支払者：<%= @money.user_name %><br>
                <br>
                商品名：<%= @money.item_name %><br>
                <br>
                金額：<%= @money.price %>円
              </h4>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</main>