config/routes.rb
Rails.application.routes.draw do
  devise_for :houses
  root to: "pages#toppage"
  resources :users
  resources :rules
  resources :money
  resources :works
  resources :todos
  resources :schedules
  resources :chats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :house
  has_one_attached :image

  with_options presence: true do
    validates :user_name
    validates :talk
  end
end

app/models/house.rb
class House < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users
  has_many :chats
  has_many :rules
  has_many :money
  has_many :works
  has_many :schedules
  has_many :todos

  with_options presence: true do
    validates :house_name
    validates :address
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/money.rb
class Money < ApplicationRecord
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :item_name
    validates :price, format: { with: /\A[0-9]+\z/ }
    validates :price, numericality: true
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :title
    validates :content
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :start_time
    validates :event
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :list
    validates :limit
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chats
  has_many :rules
  has_many :money
  has_many :works
  has_many :schedules
  has_many :todos
  has_one_attached :image
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :birthday
    validates :image
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :work_name
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_house!
  before_action :set_users, only: [:index, :edit]
  before_action :set_find_chat, only: [:show, :edit, :update, :destroy]
  before_action :set_redirect, only: [:show, :edit]

  def index
    @chat = Chat.new
    @chats = Chat.all.order(id: 'DESC')
  end

  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      redirect_to action: :index
    else
      @chats = Chat.all.order(id: 'DESC')
      @users = User.where(house_id: current_house.id)
      render :index
    end
  end

  def show
  end

  def edit
  end

  def update
    if @chat.update(chat_params)
      redirect_to chat_path(@chat)
    else
      @users = User.where(house_id: current_house.id)
      render :edit
    end
  end

  def destroy
    @chat.destroy
    redirect_to chats_path
  end

  private

  def chat_params
    params.require(:chat).permit(:talk, :image, :user_name).merge(house_id: current_house.id)
  end

  def set_users
    @users = User.where(house_id: current_house.id)
  end

  def set_find_chat
    @chat = Chat.find(params[:id])
  end

  def set_redirect
    redirect_to root_path if @chat.house_id != current_house.id
  end
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  before_action :authenticate_house!
  before_action :set_users, only: [:index, :new, :edit]
  before_action :set_find_money, only: [:show, :edit, :update, :destroy]
  before_action :set_redirect, only: [:show, :edit]

  def index
    @money = Money.all.order(id: 'DESC')
  end

  def new
    @money = Money.new
  end

  def create
    @users = User.all
    @money = Money.new(money_params)
    if @money.save
      redirect_to money_index_path
    else
      @users = User.where(house_id: current_house.id)
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @money.update(money_params)
      redirect_to money_path(@money)
    else
      @users = User.where(house_id: current_house.id)
      render :edit
    end
  end

  def destroy
    @money.destroy
    redirect_to money_index_path
  end

  private

  def money_params
    params.require(:money).permit(:item_name, :price, :user_name).merge(house_id: current_house.id)
  end

  def set_users
    @users = User.where(house_id: current_house.id)
  end

  def set_find_money
    @money = Money.find(params[:id])
  end

  def set_redirect
    redirect_to root_path if @money.house_id != current_house.id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_house!
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :authenticate_house!
  before_action :set_users, only: [:new, :edit]
  before_action :set_find_rule, only: [:show, :edit, :update, :destroy]
  before_action :set_redirect, only: [:show, :edit]

  def index
    @rules = Rule.all
  end

  def new
    @rule = Rule.new
  end

  def create
    @users = User.all
    @rule = Rule.new(rule_params)
    if @rule.save
      redirect_to rules_path
    else
      @users = User.where(house_id: current_house.id)
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @rule.update(rule_params)
      redirect_to rule_path(@rule)
    else
      @users = User.where(house_id: current_house.id)
      render :edit
    end
  end

  def destroy
    @rule.destroy
    redirect_to rules_path
  end

  private

  def rule_params
    params.require(:rule).permit(:title, :content, :user_name).merge(house_id: current_house.id)
  end

  def set_users
    @users = User.where(house_id: current_house.id)
  end

  def set_find_rule
    @rule = Rule.find(params[:id])
  end

  def set_redirect
    redirect_to root_path if @rule.house_id != current_house.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>シェアハウス管理アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <style>
      .container1 {
        background-color: #ffeddc;
      }
      .card {
        background-color: #f5f5f5;
      }
      a {
        color: black;
      }
      a:hover {
        text-decoration: none;
      }
      .top-logo {
        width: 100%;
        height: 200px;
      }
      .users-logo {
        width: 100%;
        height: 220px;
      }
      .show-logo {
        width: 100%;
        height: 520px;
      }
      .chats-logos {
        width: 80px;
        height: 80px;
      }
      li {
        list-style: none;
      }
    </style>
  </head>

  <body class="bg-light">
    <header>
      <div class="container1 text-center">
        <div class="row">
          <div class="title col-7">
            <h4 class="m-3 p-2"><a href="/">シェアハウス管理アプリ</h4>
          </div>
          <div class="devise col-5">
            <% if house_signed_in? %>
              <h6 class="m-3 p-3">
                <%= link_to current_house.house_name, edit_house_registration_path(current_house) %>
                <%= link_to "ログアウト", destroy_house_session_path, method: :delete %>
              </h6>
            <% else %>
              <h6 class="m-3 p-3">
                <%= link_to "新規登録", new_house_registration_path %>
                <%= link_to "ログイン", new_house_session_path %>
              </h6>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container1 text-center">
        <div class="row">
          <div class="title col-12">
            <p class="m-1 p-1"><a href="/">SHARE HOUSE MANAGEMENT APP @2021</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/toppage.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">メニュー</h3>
      <p class="lead text-muted">シェアハウスを新規登録またはログインされた新たな住民の方は最初に住民登録を行ってください。ルームメイトから住民登録を行うと他の機能で登録した住民が選択できるようになります。</p>
    </div>
  </div>
</section>

<main>
  <div class="menu text-center">
    <div class="container">
      <div class="row row-cols-2 row-cols-md-4">
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("house.jpeg", class:"top-logo"), edit_house_registration_path(current_house) %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "シェアハウス", edit_house_registration_path(current_house) %>
              </p>
            </div>
          </div>
        </div>
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("user.jpg", class: "top-logo"), users_path %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "ルームメイト", users_path %>
              </p>
            </div>
          </div>
        </div>
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("chat.jpeg", class: "top-logo"), chats_path %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "チャット", chats_path %>
              </p>
            </div>
          </div>
        </div>
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("schedule.jpg", class:"top-logo"), schedules_path %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "スケジュール", schedules_path %>
              </p>
            </div>
          </div>
        </div>
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("rule.jpg", class: "top-logo"), rules_path %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "ルール", rules_path %>
              </p>
            </div>
          </div>
        </div>
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("list.jpg", class: "top-logo"), todos_path %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "TODO", todos_path %>
              </p>
            </div>
          </div>
        </div>
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("money.jpg", class:"top-logo"), money_index_path %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "マネー", money_index_path %>
              </p>
            </div>
          </div>
        </div>
        <div class="col mb-5">
          <div class="card shadow-sm">
            <%= link_to image_tag("work.jpg", class: "top-logo"), works_path %>
            <div class="card-body">
              <p class="card-text">
                <%= link_to "ワーク", works_path %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>