config/routes.rb
Rails.application.routes.draw do
  devise_for :houses
  root to: "pages#toppage"
  resources :users
  resources :rules
  resources :money
  resources :works
  resources :todos
  resources :schedules
  resources :chats
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :house

  with_options presence: true do
    validates :user_name
    validates :title
    validates :content
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :authenticate_house!
  before_action :set_users, only: [:new, :edit]
  before_action :set_find_rule, only: [:show, :edit, :update, :destroy]
  before_action :set_redirect, only: [:show, :edit]

  def index
    @rules = Rule.all
  end

  def new
    @rule = Rule.new
  end

  def create
    @users = User.all
    @rule = Rule.new(rule_params)
    if @rule.save
      redirect_to rules_path
    else
      @users = User.where(house_id: current_house.id)
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @rule.update(rule_params)
      redirect_to rule_path(@rule)
    else
      @users = User.where(house_id: current_house.id)
      render :edit
    end
  end

  def destroy
    @rule.destroy
    redirect_to rules_path
  end

  private

  def rule_params
    params.require(:rule).permit(:title, :content, :user_name).merge(house_id: current_house.id)
  end

  def set_users
    @users = User.where(house_id: current_house.id)
  end

  def set_find_rule
    @rule = Rule.find(params[:id])
  end

  def set_redirect
    redirect_to root_path if @rule.house_id != current_house.id
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/edit.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">ルール編集</h3>
      <p class="lead text-muted">ルールの編集が可能です。</p>
      <p>
        <%= link_to "詳細に戻る", rule_path(@rule.id), class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<div class="card col-sm-6 mx-auto mb-5">
  <div class="card-body text-center mx-auto">
    <h4 class="mt-1 mb-3">ルール編集</h4><br>
    <%= form_with(model: @rule, local: true) do |form| %>
     <%= render 'layouts/error_messages', model: form.object %>

      <div class="form-group">
        <%= form.select :user_name, @users.map{ |user| user.user_name }, include_blank: "作成者を選択" %>
      </div>

      <div class="form-group">
        <%= form.text_field :title, autocomplete: "off", placeholder: "タイトル" %>
      </div>

      <div class="form-group">
        <%= form.text_area :content, autocomplete: "off", rows: "7" %>
      </div>

      <div class="actions">
        <%= form.submit "変更", :class => "btn btn-outline-dark disabled" %>
      </div>

    <% end %>
  </div>
</div>

app/views/rules/index.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">ルール一覧</h3>
      <p class="lead text-muted">共同生活を行う上でルールは必ず守りましょう。クリックすると詳細画面へ移動します。</p>
      <p>
        <%= link_to "新規作成", new_rule_path, class: "btn btn-outline-info my-2" %>
        <%= link_to "メニューに戻る", root_path, class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<main>
  <div class="container text-center">
    <div class="row row-cols-2 row-cols-md-3">
      <% @rules.each do |rule| %>
        <% if current_house.id == rule.house_id %>
          <div class="col-md-4">
            <div class="border mb-4 shadow-sm">
              <div class="col p-4 flex-column">
                <strong class="d-inline-block mb-2 text-secondary">
                  作成者:<%= rule.user_name %>
                </strong>
                <h4 class="mt-2">
                  <%= rule.title %>
                </h4>
                <br>
                <%= link_to "詳細確認", rule_path(rule.id), class: "btn btn-outline-secondary btn-sm" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/rules/new.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">ルール作成</h3>
      <p class="lead text-muted">ルールの作成が可能です。</p>
      <p>
        <%= link_to "一覧に戻る", rules_path, class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<div class="card col-sm-6 mx-auto mb-5">
  <div class="card-body text-center mx-auto">
    <h4 class="mt-1 mb-3">ルール内容</h4><br>
    <%= form_with(model: @rule, local: true) do |form| %>
     <%= render 'layouts/error_messages', model: form.object %>

      <div class="form-group">
        <%= form.select :user_name, @users.map{ |user| user.user_name }, include_blank: "作成者を選択" %>
      </div>

      <div class="form-group">
        <%= form.text_field :title, autocomplete: "off", placeholder: "タイトル" %>
      </div>

      <div class="form-group">
        <%= form.text_area :content, autocomplete: "off", rows: "7" %>
      </div>

      <div class="actions">
        <%= form.submit "作成", :class => "btn btn-outline-dark disabled" %>
      </div>

    <% end %>
  </div>
</div>

app/views/rules/show.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h3 class="fw-light">ルール詳細</h3>
      <p class="lead text-muted">ルールの詳細確認・編集・削除が可能です。</p>
      <p>
        <%= link_to "編集", edit_rule_path, class: "btn btn-outline-success my-2" %>
        <%= link_to "削除", rule_path, method: :delete, class: "btn btn-outline-danger my-2" %>
        <%= link_to "一覧に戻る", rules_path, class: "btn btn-outline-warning my-2" %>
      </p>
    </div>
  </div>
</section>
<main>
  <div class="card col-sm-10 mx-auto mb-5">
    <div class="card-body text-center mx-auto">
      <% if current_house.id == @rule.house_id %>
        <div class="col my-5">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4 class="card-text">
                投稿者：<%= @rule.user_name %><br>
                <br>
                タイトル：<%= @rule.title %><br>
                <br>
                内容<br>
                <br>
                <%= simple_format (@rule.content) %>
              </h4>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</main>